name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --base-href="/turnauskaavio/"

      # Clone the target repository first
      - name: Clone target repository
        run: |
          git clone https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/kalub70/kalub70.github.io.git target-repo
      
      # Copy your build files
      - name: Copy build files
        run: |
          mkdir -p target-repo/turnauskaavio
          cp -r dist/turnaus/browser/* target-repo/turnauskaavio/
      
      # Commit and push changes
      - name: Commit and push
        run: |
          cd target-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy turnauskaavio from private repo"
          git push